version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Profi123987"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  docker-multi-stage:
    depends_on:
      - db
    image: docker-multi-stage-build:2.0-SNAPSHOT
    container_name: docker-multi-stage
    ports:
      - "8080:8080"
volumes:
  postgres-data: